name: 'Run default CI jobs'

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 2
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10', '3.11', '3.12', '3.13']
        workspace: ['locked', 'latest']
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v6
      - name: 'Configure workspace'
        run: |
          echo ${{ matrix.python }} > .python-version
          uv sync --all-groups --all-extras ${{ (matrix.workspace == 'latest' && '-U') || '--frozen' }}
      - name: Lint sources
        run: |
          uv run black --check .
      - name: Check buildable
        run: uv build
      - name: Run test
        run: |
          uv run pytest
